DROP TABLE IF EXISTS playlist_musicas;
DROP TABLE IF EXISTS reproducoes;
DROP TABLE IF EXISTS playlists;
DROP TABLE IF EXISTS musicas;

CREATE TABLE musicas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    artista VARCHAR(150) NOT NULL,
    album VARCHAR(150),
    duracao INTEGER NOT NULL CHECK (duracao > 0),
    genero VARCHAR(50)
);

CREATE TABLE playlists (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255)
);

CREATE TABLE playlist_musicas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlistid INT NOT NULL,
    musicaid INT NOT NULL,
    FOREIGN KEY (playlistid) REFERENCES playlists(id),
    FOREIGN KEY (musicaid) REFERENCES musicas(id),
    UNIQUE (playlistid, musicaid)
);

CREATE TABLE reproducoes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlistid INT NOT NULL,
    datahora TIMESTAMP NOT NULL,
    FOREIGN KEY (playlistid) REFERENCES playlists(id)
);
